Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Templates/EmailContent.cs
Backend/PlantillasHtml/PlantillaBienvenida.html
Backend/PlantillasHtml/PlantillaContra.html

Cambios en las plantillas de correos electrónicos 
Envío de correos electrónicos de bienvenida y regeneración de contraseña

Arreglos en el envío de correos electrónicos

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Models/ChangePassRequest.cs
Backend/HireAProBackend/Models/ForgotPassRequest.cs
Backend/HireAProBackend/Models/Jwt.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/Templates/EmailContent.cs
Backend/HireAProBackend/appsettings.json

- Creación de un jwt para la regeneración de contraseña
- Añadida un key de jwt llamada ResetPassKey y cambios en el appsettings.json y Program.cs
- Comprobación jwt y cambio de contraseña

Comprobación del token de regenerar contraseña funcional

---

Angular/src/app/auth.service.ts
Angular/src/app/forgot-password/forgot-password.component.html
Angular/src/app/forgot-password/forgot-password.component.ts

Se ha implementado:
-
- Se ha añadido la doble vista en el Componente "forgot-password"
- Se ha añadido 2 métodos mas al auth.service
- Se ha implementado el control de errores para el "forgot-password"
Falta acabar:
-
- postForgotChange() y el ForgotChange()

Primera Parte del "Forgot Password"

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Models/RegisterRequest.cs
Backend/HireAProBackend/Models/Usuario.cs

- Token de recuperación de la contraseña se envía en el body de la http request
- Cambios inacabados en el register
- Cambios en el modelo Usuario.cs, añadido el booleano verified y el campo username
- Configuración inacabada de correo de verificación al registrar

Token recuperación enviada en el body de la request

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Templates/EmailContent.cs

- Plantillas de correo electrónicos con mínimos cambios estéticos
- Añadida una ruta de verifyAccount para comprobar la validez del token
- Añadido un timeout a la función de verificar la cuenta

Verificación de la cuenta al registrar

---

Backend/HireAProBackend/Services/DelUsersService.cs

**Cambios terminados**
- Función de Register que envía un token de verifcación por correo electrónico
- Creada la plantilla html para  el correo de verificación
- Función VerifyAccount que verifica la validez del token
**Por hacer**
- Crear plantilla html para reenviar el correo de verificación
- Terminar el servicio de eliminación de usuarios no verificados

Verificación de usuarios

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Models/TokenPassReset.cs

**Cambios realizados:**
- Login mediante nombre de usuario
- Caducidad en el token pasados 15 minutos, impidiendo usar ese token para cambiar la ocntraseña.
- Eliminación de tokens de recuperación una vez restablecida la contraseña, para no hacer bulto en la base de datos

Actualización en el login

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Models/CompleteProfileRequest.cs
Backend/HireAProBackend/Models/Usuario.cs

- Nueva función httpPOST 'CompleteProfile' para terminar de rellenar la información personal y actualizarla cuando se quiera
- Creación del modelo 'CompleteProfileRequest.cs' para la función
- Modificación del modelo 'Usuarios.cs' con los nuevos campos añadidos

Crear httpPOST completeProfile y modificar campos de FireStore 'Usuarios'

---

Backend/HireAProBackend/Controllers/Controlador.cs

**Cambios añadidos**
- Solo se puede iniciar sesión con cuentas que estén previamente verificadas

Autentificación del login solamente para cuentas verificadas

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/appsettings.json
Backend/PlantillasHtml/PlantillaVerificacion7dias.html

**Cambios**
- Creada la plantilla de correo electrónico de recordar verificar
- Conexión a la base de datos en el Program.cs
- Añadida información en el appsettings.json sobre la base de datos
**Pendiente**
- Enviar el correo electrónico de recordar verificar

Cambiada la conexión de la base de datos y plantilla html

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Models/Usuario.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/Services/DelUsersService.cs

- Configurado el servicio de verificación de cuentas y eliminación de cuentas no verificadas

Verificación cuentas funcional

---

Angular/src/app/auth.service.ts
Angular/src/app/login/login.component.html
Angular/src/assets/css/auth.css

Se ha cambiado:
- 
- Los placeholders del login (se ha dejado un espacio)
- Se ha hecho global la variable headers (para optimizar la lectura del codigo)
- Se ha arreglado las validaciones del auth para el username para permitirlo.
- Se ha cambiado el display del formulario a un grid y un flex para pantallas pequeñas para hacerla mas responsiva.

Cambiar placeholder user password, variable global para los headers, parch en las validaciones de username y Mejoras en el CSS

---

Backend/HireAProBackend/Templates/EmailContent.cs

- Modificadas las templates de correo electrónico

Modificadas las templates de correo electrónico

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/Services/IShaHash.cs
Backend/HireAProBackend/Services/ShaHash.cs

**Cambios:**
- Función del ShaHash convertida a un servicio transient
- Servicio inyectado en el controlador
- Función eliminada del controlador para mantener el código limpio

Funcion ShaHash como servicio

---

Angular/src/assets/css/404.css
Angular/src/assets/css/loading.css

Adaptación de estilos en 404 y loading

404 y loading - Cambios de estilos adaptados al auth

---

Backend/HireAProBackend/Controllers/Controlador.cs

- Cambio de un StatusCode de 401 a 503 en forgotPassword

Cambio en un statuscode

---

Backend/HireAProBackend/Services/GenTokenRecuperacion.cs
Backend/HireAProBackend/Services/IGenTokenRecuperacion.cs

Crear documentos en la carpeta Servicios:
- GenTokenRecuperacion
- IGenTokenRecuperacion
PAra no tener conflicto con las otras pull requests, he dejado la función generarTokenRecuperacion al controlador, falta modificar el Controlador.cs

Servicio Generar Token

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/Services/GenTokenReset.cs
Backend/HireAProBackend/Services/IGenTokenReset.cs

Añadido el servicio GenTokenReset en Controlador.cs y Program.cs.
Eliminada la función generarToken del Controlador (función ya inservible).

Inyectar servicio GenTokenReset

---

Angular/package-lock.json

Se arreglan problemas de seguridad

npm audit fix

---

Backend/HireAProBackend/Controllers/Controlador.cs
Backend/HireAProBackend/Program.cs
Backend/HireAProBackend/Services/ISaveToken.cs
Backend/HireAProBackend/Services/SaveToken.cs

**Cambios:**
- Creado el servicio SaveToken
- Inicializado en el Program.cs
- Limpiado el código del controlador
- Todos los servicios 100% funcionales

Creado el sevricio SaveToken

---

Angular/src/styles.css

Cambiar el color del  **background** al root.

Cambiar el color 

---

Angular/src/app/auth.service.ts
Angular/src/app/register/register.component.html
Angular/src/app/register/register.component.ts
Angular/src/assets/css/auth.css
Angular/src/index.html

Se ha implementado:
- 
- Un CSS bonito
- El auth service funciona haciendo la request
Falta arreglar:
- 
- En el backend falta que guarde la var type en la base de datos
- Optimizar el CSS

Añadida la opción de registrarse como cliente o professional

---

Angular/src/app/auth.service.ts
Angular/src/app/register/register.component.html
Backend/docker-compose.yml
Backend/enter-docker.ps1
Backend/start-docker.ps1
Backend/stop-docker.ps1

Mejoras realizadas:
-
- Las variables de URL ahora se definen como constantes para mayor consistencia.
- Se han creado funciones específicas para validaciones, reduciendo redundancia en el código y mejorando la legibilidad.
---
Próximos pasos:
-
- Hacer pruebas para asegurar el correcto funcionamiento de las nuevas implementaciones.

Refactorización de Variables y Validaciones

---

Angular/src/styles.css

- Cambio de color background de landing

Canbio fondo landing page

---

README.md

Se actualiza:
-
- Los enlaces del README con iconos y descripciones.

Mejora de los enlaces en el README
